### ISSUE TITLE
support add this repo as component (IDFGH-7672)

### ISSUE THREAD

**Issue by phatpaul** [espressif/idf-flash-vendor-patches#1] opened 2022-06-23 15:05 UTC
Split this repo into a component and an example which includes it as a submodule.
That way I don't have to copy/paste the code into my project, I can easily add this to my project as a submodule in /components.

**Comment by igrr** [comment] 2022-06-23 15:17
@phatpaul We might need to add more components to this project (although we hope we don't have to...) so we would prefer to keep the existing structure.

I think you can still add this as a submodule (not into the `components` directory), then set EXTRA_COMPONENT_DIRS in your project to point to the component location:
```cmake
set(EXTRA_COMPONENT_DIRS ${CMAKE_CURRENT_LIST_DIR}/../patches/idf-flash-vendor-patches/components/idf-flash-vendor-patches)
```

Another option, in IDF v4.2.2 and later, it is also possible to install this component using the [IDF component manager](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html). For example, by adding an `idf_component.yml` file to one of your project's components, with the following contents:
```
dependencies:
  idf-flash-vendor-patches:
    path: components/idf-flash-vendor-patches
    git: https://github.com/espressif/idf-flash-vendor-patches.git
```

**Comment by phatpaul** [comment] 2022-06-23 16:04
Thanks for the great tips!

**Comment by phatpaul** [comment] 2022-08-10 19:09
This tip from @igrr worked great.  I recommend adding this to the readme in this example.  I can do it with a PR if you want.

BTW, igrr's instructions said "adding an idf_component.yml file to one of your project's components", which I found to be slightly ambiguous.  I just added the idf_component.yml to my project's /main/ folder and then ran `idf reconfigure` and it worked.

**Comment by phatpaul** [comment] 2022-09-20 14:49
The managed_component approach is working OK except there is this annoying thing that happens occasionally.  I never touched any of the files in /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/managed_components/idf-flash-vendor-patches
And git does not report any changes (this folder is not in my version control).
But sometimes after a clean and rebuild I get this error:
```
-- Building ESP-IDF components for target esp32
Processing 1 dependencies:
[1/1] idf-flash-vendor-patches (d30546dc9903a40d0275f748185bd5a41be620da)
CMake Error at /home/pabbott/repos/esp32-idf4/tools/esp-idf/tools/cmake/build.cmake:432 (message):
  ERROR:
          Some components (idf-flash-vendor-patches) in the "managed_components" directory were modified         on the disk since the last run of the CMake. Content of this directory is managed automatically.
          If you want to keep the changes, you can move the directory with the component to the "components"         directory of your project.
          I.E. for "idf-flash-vendor-patches" run:
          mv /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/managed_components/idf-flash-vendor-patches /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/components/idf-flash-vendor-patches
          Or, if you want to discard the changes remove the ".component_hash" file from the component's directory.
          I.E. for "idf-flash-vendor-patches" run:
          rm /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/managed_components/idf-flash-vendor-patches/.component_hash
          
Call Stack (most recent call first):
  /home/pabbott/repos/esp32-idf4/tools/esp-idf/tools/cmake/project.cmake:371 (idf_build_process)
  CMakeLists.txt:21 (project)

-- Configuring incomplete, errors occurred!
See also "/home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/build/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja 
/usr/bin/cmake -S/home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd -B/home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/build
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
```
The error message is helpful and it's easy to fix.  But why is this happening?

**Comment by kumekay** [comment] 2022-09-26 16:38
Hi @phatpaul 
So far, I wasn't able to reproduce your problem. When it will happen next time, could you please try running these commands and share the output:

```
ls -latR managed_components/idf-flash-vendor-patches
cat managed_components/idf-flash-vendor-patches/.component_hash
rm cat managed_components/idf-flash-vendor-patches/.component_hash
idf.py reconfigure
ls -latR managed_components/idf-flash-vendor-patches
cat managed_components/idf-flash-vendor-patches/.component_hash
python -m idf_component_manager --help
```

To check if there are any modified files and the version of the component manager.

**Comment by phatpaul** [comment] 2022-09-26 18:09
Thanks for taking a look @kumekay 
```
$ idf fullclean
Executing action: fullclean
Executing action: remove_managed_components
ERROR: 
        Some components (idf-flash-vendor-patches) in the "managed_components" directory were modified         on the disk since the last run of the CMake. Content of this directory is managed automatically.

        If you want to keep the changes, you can move the directory with the component to the "components"         directory of your project.

        I.E. for "idf-flash-vendor-patches" run:
        mv /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/managed_components/idf-flash-vendor-patches /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/components/idf-flash-vendor-patches

        Or, if you want to discard the changes remove the ".component_hash" file from the component's directory.

        I.E. for "idf-flash-vendor-patches" run:
        rm /home/pabbott/repos/esp32-idf4/esp-eth-libesphttpd/managed_components/idf-flash-vendor-patches/.component_hash

```
```sh
$ ls -latR managed_components/idf-flash-vendor-patches/
managed_components/idf-flash-vendor-patches/:
total 32
drwxrwxr-x 2 pabbott pabbott 4096 Sep 20 11:11 .
drwxrwxr-x 3 pabbott pabbott 4096 Sep 20 11:11 ..
-rw-rw-r-- 1 pabbott pabbott   64 Sep 20 11:11 .component_hash
-rw-rw-r-- 1 pabbott pabbott  196 Sep 20 11:11 CMakeLists.txt
-rw-rw-r-- 1 pabbott pabbott  375 Sep 20 11:11 linker.lf
-rw-rw-r-- 1 pabbott pabbott 6768 Sep 20 11:11 xmc_lock_sr.c
-rw-rw-r-- 1 pabbott pabbott 2798 Sep 20 11:11 xmc_lock_sr.h

$ cat managed_components/idf-flash-vendor-patches/.component_hash 
e0e7d913871290358cdc49b3979c750eba655b92e8491727e1a6120820466192

$ rm managed_components/idf-flash-vendor-patches/.component_hash

$ idf reconfigure
(... bunch of output, but I think the relevant part is:)
Processing 1 dependencies:
[1/1] idf-flash-vendor-patches (d30546dc9903a40d0275f748185bd5a41be620da)

```
```
$ ls -latR managed_components/idf-flash-vendor-patches/
managed_components/idf-flash-vendor-patches/:
total 32
drwxrwxr-x 2 pabbott pabbott 4096 Sep 26 13:49 .
drwxrwxr-x 3 pabbott pabbott 4096 Sep 26 13:49 ..
-rw-rw-r-- 1 pabbott pabbott   64 Sep 26 13:49 .component_hash
-rw-rw-r-- 1 pabbott pabbott 6768 Sep 26 13:49 xmc_lock_sr.c
-rw-rw-r-- 1 pabbott pabbott 2798 Sep 26 13:49 xmc_lock_sr.h
-rw-rw-r-- 1 pabbott pabbott  196 Sep 26 13:49 CMakeLists.txt
-rw-rw-r-- 1 pabbott pabbott  375 Sep 26 13:49 linker.lf

$ cat managed_components/idf-flash-vendor-patches/.component_hash 
e0e7d913871290358cdc49b3979c750eba655b92e8491727e1a6120820466192

$ python -m idf_component_manager --help
usage: __main__.py [-h] [--path PATH] [--namespace NAMESPACE] [--service-profile SERVICE_PROFILE] --name NAME
                   [--archive ARCHIVE] [--job JOB] [--version VERSION] [--skip-pre-release] [--check-only]
                   [--allow-existing] [--example EXAMPLE]
                   {pack-component,upload-component,upload-component-status,create-project-from-example,delete-version}

IDF component manager v1.1.4

```

**Comment by kumekay** [comment] 2022-09-27 16:32
@phatpaul Thank you for the details! 

An interesting detail that your hash sum for commit `d30546dc9903a40d0275f748185bd5a41be620da` is different.

I've tried on a few systems and always got
`9b3a0cc532241e93adb5c1f74ebaf84b4895c6c9c8e448c7065897d0494f0a3f`

Could you provide more details about your system? 
Linux distro, kernel (maybe `uname -a` output), what kind of filesystem are you using? Maybe some software that can hijack file system access?

**Comment by phatpaul** [comment] 2022-10-07 19:43
Just a normal Ubuntu linux AFAIK.  xubuntu 20.04.  fs is ext4

$ uname -a
Linux lumilab01 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I'm running vscode.  I tried the same steps while vscode is not running, but the same issue happens.

Btw I have esp-idf as a git submodule in my project.  Here's a partial tree view (note /tools/esp-idf/)  
```
$ tree -L 2
.
├── doc
├── esp-eth-libesphttpd
│   ├── build
│   ├── CMakeLists.txt
│   ├── components
│   ├── dependencies.lock
│   ├── main
│   ├── managed_components
│   │   └── idf-flash-vendor-patches
│   │       ├── CMakeLists.txt
│   │       ├── linker.lf
│   │       ├── xmc_lock_sr.c
│   │       └── xmc_lock_sr.h
│   ├── partitions.csv
│   ├── sdkconfig
│   ├── sourceme_IDF_ENV.sh
│   └── _START_IDF_ENV.cmd
├── readme.md
└── tools
    ├── check_submodules.py
    ├── esp-idf
    └── remote-capture.cmd

```

**Comment by ginkgm** [comment] 2023-01-05 03:22
I'm doing a update for the documentation. After it's merged, this issue will be closed.

The issue above seems to be a IDF component manager issue, please find another please to discuss it, thanks! @phatpaul @kumekay

**Closed as completed** 2023-01-09 07:09 UTC
Labels: Resolution: Done, Status: Done
